# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190109_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user', models.CharField(default='', max_length=32)),
                ('content', models.TextField(max_length=500)),
                ('creation_time', models.CharField(default='', max_length=32)),
                ('state', models.CharField(default='0', max_length=8)),
            ],
        ),
    ]
