# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article_part_of',
            field=models.CharField(default='', max_length=32),
        ),
    ]
