# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-12 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_com_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_good',
            field=models.IntegerField(default=0),
        ),
    ]
